export const choreCategories = [
  "Cleaning",
  "Errands",
  "Pet & plant care",
  "Moving & setup",
  "Yard care",
  "Computer help",
  "House maintenance",
  "Furniture assembly",
  "Painting and decorating",
  "Plumbing help",
  "Electrical help",
  "Appliance help",
  "Moving and lifting",
  "Delivery and pickup",
  "Grocery shopping",
  "Meal preparation",
  "Laundry and ironing",
  "Childcare",
  "Elder companionship",
  "Tutoring and homework",
  "Administrative help",
  "Event setup and cleanup",
  "Organization and decluttering",
  "Recycling and donation drop-off",
  "Snow and ice removal",
] as const;

export const choreCategorySet = new Set<string>(choreCategories);
