import { useSyncExternalStore } from "react";

export type Locale = "en" | "nl";
const STORAGE_KEY = "choreloop-locale";
const EVENT_NAME = "choreloop-locale-change";

const COPY: Record<Locale, Record<string, string>> = {
  en: {},
  nl: {
    "Home": "Home", "Discover chores": "Klussen ontdekken", "My chores": "Mijn klussen", "Credit activity": "Creditactiviteit", "Post a chore": "Plaats een klus",
    "Trade time. Get life back.": "Ruil tijd. Krijg ruimte in je leven.", "Founding member offer": "Aanbod voor eerste leden", "A little help goes a long way.": "Een beetje hulp maakt een groot verschil.", "ChoreLoop is the neighbor-to-neighbor exchange where you give an hour, get a hand, and keep the good stuff moving.": "ChoreLoop is de ruil voor buren: geef een uur, krijg hulp en houd het goede gaande.",
    "Give what you can": "Geef wat je kunt", "Post a small task or offer a skill. Every chore has a clear credit value.": "Plaats een kleine taak of bied een vaardigheid aan. Elke klus heeft een duidelijke creditwaarde.", "Ask your neighbors": "Vraag je buren", "Find help close to home, when you actually need it.": "Vind hulp dichtbij, precies wanneer je die nodig hebt.", "Keep it balanced": "Houd het in balans", "Credits move when the chore is complete. Simple, visible, fair.": "Credits bewegen wanneer de klus klaar is. Eenvoudig, duidelijk en eerlijk.",
    "Your name": "Je naam", "Neighborhood": "Buurt", "Join free": "Gratis meedoen", "First 1,000 members get 100 credits.": "De eerste 1.000 leden krijgen 100 credits.", "No card. No catch.": "Geen kaart. Geen addertje onder het gras.", "Welcome back": "Welkom terug", "You’re on the list": "Je staat op de lijst", "Find a chore": "Vind een klus", "Loading your exchange…": "Jouw ruiloverzicht laden…", "Your balance": "Jouw saldo", "credits": "credits", "View activity": "Bekijk activiteit", "Founding member spots": "Plekken voor eerste leden", "/ 1,000 joined": "/ 1.000 aangemeld", "North Loop": "North Loop", "Your 100-credit welcome grant is active.": "Je welkomsttegoed van 100 credits is actief.", "You joined after the launch grant filled.": "Je bent aangemeld nadat het starttegoed op was.", "Near": "In de buurt van", "Chores that need a hand": "Klussen die hulp nodig hebben", "See all": "Bekijk alles",
    "The neighborhood board": "Het buurtbord", "Find a chore to trade": "Vind een klus om te ruilen", "Offer help": "Hulp aanbieden", "Couldn’t load chores": "Klussen konden niet worden geladen", "No open chores in this category yet.": "Nog geen open klussen in deze categorie.", "Chore claimed — make it yours": "Klus aangenomen — maak hem van jou",
    "e.g. Help move a sofa upstairs": "bijv. Help een bank naar boven te verplaatsen", "Start an exchange": "Start een ruil", "What do you need help with?": "Waar heb je hulp bij nodig?", "This Saturday morning": "Zaterdagmorgen", "A few details": "Enkele details", "(optional)": "(optioneel)", "Anything a neighbor should know before they say yes?": "Wat moet een buur weten voordat die ja zegt?", "Cancel": "Annuleren", "Posting…": "Plaatsen…", "Your chore is live on the board": "Je klus staat op het bord", "Post chore": "Klus plaatsen",
    "Your exchange desk": "Jouw ruiloverzicht", "Posted by you": "Door jou geplaatst", "You accepted": "Door jou aangenomen", "Arrange the details": "Stem de details af", "Mark complete": "Markeer als voltooid", "Edit chore": "Klus bewerken", "When someone accepts, you can chat here to arrange the handoff.": "Zodra iemand de klus aanneemt, kun je hier chatten om de overdracht af te stemmen.", "Posted or accepted chores will appear here.": "Geplaatste of aangenomen klussen verschijnen hier.", "Exchange complete — credits settled": "Ruil voltooid — credits verrekend",
    "Your credit trail": "Jouw creditgeschiedenis", "Activity": "Activiteit", "Available credits": "Beschikbare credits", "Use them when you need a hand.": "Gebruik ze wanneer je hulp nodig hebt.", "Spend credits": "Credits uitgeven", "Recent activity": "Recente activiteit",
    "No messages yet. Say hello and agree on the details.": "Nog geen berichten. Zeg hallo en stem de details af.", "Loading conversation…": "Gesprek laden…", "Message the chore poster": "Bericht aan de plaatser", "Confirm timing, access, or other details…": "Bevestig tijd, toegang of andere details…", "This completed conversation is read-only.": "Dit voltooide gesprek is alleen-lezen.", "Sending…": "Versturen…", "Send message": "Bericht versturen", "Couldn’t load messages": "Berichten konden niet worden geladen", "Couldn’t send message": "Bericht kon niet worden verstuurd",
    "Title": "Titel", "Credits": "Credits", "Details": "Details", "Saving…": "Opslaan…", "Save changes": "Wijzigingen opslaan", "Chore updated": "Klus bijgewerkt", "Couldn’t save chore": "Klus kon niet worden opgeslagen",
    "English": "English", "Nederlands": "Nederlands", "Language": "Taal", "Loading": "Laden", "Close navigation": "Navigatie sluiten", "Open navigation": "Navigatie openen", "Expand sidebar": "Zijbalk uitklappen", "Collapse sidebar": "Zijbalk inklappen", "icon": "pictogram", "Page not found": "Pagina niet gevonden", "Back Home": "Terug naar home",
    "open": "Open", "claimed": "Aangenomen", "completed": "Voltooid", "cancelled": "Geannuleerd", "All": "Alle", "Cleaning": "Schoonmaak", "Errands": "Boodschappen en klusjes", "Pet & plant care": "Huisdieren- en plantenverzorging", "Moving & setup": "Verhuizen en opzetten", "Yard care": "Tuinonderhoud", "Computer help": "Computerhulp", "House maintenance": "Woningonderhoud", "Furniture assembly": "Meubelmontage", "Painting and decorating": "Schilderen en decoreren", "Plumbing help": "Hulp bij loodgieterswerk", "Electrical help": "Hulp bij elektriciteit", "Appliance help": "Hulp met apparaten", "Moving and lifting": "Verhuizen en tillen", "Delivery and pickup": "Bezorgen en ophalen", "Grocery shopping": "Boodschappen doen", "Meal preparation": "Maaltijden bereiden", "Laundry and ironing": "Wassen en strijken", "Childcare": "Kinderopvang", "Elder companionship": "Gezelschap voor ouderen", "Tutoring and homework": "Bijles en huiswerk", "Administrative help": "Administratieve hulp", "Event setup and cleanup": "Evenement opbouwen en opruimen", "Organization and decluttering": "Organiseren en opruimen", "Recycling and donation drop-off": "Recycling en donaties wegbrengen", "Snow and ice removal": "Sneeuw en ijs verwijderen",
    "Add your name and neighborhood to join": "Vul je naam en buurt in om mee te doen", "You’re in — 100 credits added": "Je doet mee — 100 credits toegevoegd", "You’re on the ChoreLoop member list": "Je staat op de ChoreLoop-ledenlijst", "Name and neighborhood are required": "Naam en buurt zijn verplicht", "Choose a supported chore category": "Kies een ondersteunde kluscategorie", "Credits must be a positive whole number": "Credits moeten een positief heel getal zijn", "Join ChoreLoop before posting a chore": "Word lid van ChoreLoop voordat je een klus plaatst", "Join ChoreLoop before accepting a chore": "Word lid van ChoreLoop voordat je een klus aanneemt", "Chore not found": "Klus niet gevonden", "This chore is no longer open": "Deze klus staat niet meer open", "You cannot claim your own chore": "Je kunt je eigen klus niet aannemen", "Title, neighborhood, and timing are required": "Titel, buurt en tijdstip zijn verplicht", "Only the chore owner or an admin can edit this chore": "Alleen de eigenaar of een admin kan deze klus bewerken", "Completed chores cannot be edited": "Voltooide klussen kunnen niet worden bewerkt", "Only the chore owner can complete a claimed chore": "Alleen de eigenaar kan een aangenomen klus voltooien", "Claiming member is unavailable": "Het aangenomen lid is niet beschikbaar", "Only exchange participants can view this chat": "Alleen deelnemers aan deze ruil kunnen deze chat bekijken", "Message must be 1–2,000 characters": "Een bericht moet 1–2.000 tekens bevatten", "Chat is available only to the poster and accepted helper": "De chat is alleen beschikbaar voor de plaatser en de aangenomen helper", "Internal error": "Interne fout", "Validation failed": "Validatie mislukt",
  },
};

function readLocale(): Locale { if (typeof window === "undefined") return "en"; return localStorage.getItem(STORAGE_KEY) === "nl" ? "nl" : "en"; }
function subscribe(listener: () => void) { if (typeof window === "undefined") return () => undefined; window.addEventListener(EVENT_NAME, listener); return () => window.removeEventListener(EVENT_NAME, listener); }
export function setLocale(locale: Locale) { if (typeof window === "undefined") return; localStorage.setItem(STORAGE_KEY, locale); document.documentElement.lang = locale; window.dispatchEvent(new Event(EVENT_NAME)); }
export function translate(value: string, locale: Locale = readLocale()) { return COPY[locale][value] ?? value; }
export function useLocale() { const locale = useSyncExternalStore(subscribe, readLocale, () => "en" as Locale); return { locale, setLocale, t: (value: string) => translate(value, locale) }; }
