import { and, desc, eq, or, sql } from "drizzle-orm";
import { db } from "@/db";
import { bootstrapModule } from "./bootstrap";
import { choreMessages, creditEvents, chores, members, type Member } from "@/db/schema";
import { HttpError } from "@/lib/route-handlers";
import { choreCategorySet } from "@/lib/chore-categories";

const moduleReady = bootstrapModule("choreloop", [
  { table: members, createTable: sql`create table if not exists ${members} (id text primary key, display_name text not null, neighborhood text not null, credits integer not null default 0, welcome_grant boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now())`, createIndexes: [sql`create index if not exists chore_members_created_idx on ${members} (created_at)`], seed: async (tx) => { await tx.insert(members).values([{ id: "demo-ava", displayName: "Ava", neighborhood: "North Loop", credits: 140, welcomeGrant: true }, { id: "demo-mateo", displayName: "Mateo", neighborhood: "North Loop", credits: 82, welcomeGrant: true }]).onConflictDoNothing(); } },
  { table: chores, createTable: sql`create table if not exists ${chores} (id text primary key, title text not null, category text not null, neighborhood text not null, timing text not null, details text, credits integer not null, posted_by text not null, claimed_by text, status text not null default 'open', created_at timestamptz not null default now(), updated_at timestamptz not null default now())`, createIndexes: [sql`create index if not exists chore_offers_status_idx on ${chores} (status)`], seed: async (tx) => { await tx.insert(chores).values([{ id: "chore-1", title: "Help unpack a grocery delivery", category: "Errands", neighborhood: "North Loop", timing: "Today · 6–8 pm", details: "Two flights of stairs, about 20 minutes.", credits: 25, postedBy: "demo-ava", status: "open" }, { id: "chore-2", title: "Tidy a small balcony", category: "Cleaning", neighborhood: "North Loop", timing: "This weekend", details: "Sweep, wipe down surfaces, and bag leaves.", credits: 40, postedBy: "demo-mateo", status: "open" }, { id: "chore-3", title: "Water plants while I’m away", category: "Pet & plant care", neighborhood: "Riverside", timing: "Tomorrow morning", details: "Five plants, simple instructions provided.", credits: 30, postedBy: "demo-ava", status: "claimed", claimedBy: "demo-mateo" }, { id: "chore-4", title: "Assemble a hallway shoe rack", category: "Moving & setup", neighborhood: "North Loop", timing: "Completed yesterday", details: "Basic flat-pack assembly.", credits: 35, postedBy: "demo-mateo", status: "completed", claimedBy: "demo-ava" }]).onConflictDoNothing(); } },
  { table: creditEvents, createTable: sql`create table if not exists ${creditEvents} (id text primary key, member_id text not null, chore_id text, kind text not null, amount integer not null, note text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now())`, createIndexes: [sql`create index if not exists chore_credit_events_member_idx on ${creditEvents} (member_id, created_at)`], seed: async (tx) => { await tx.insert(creditEvents).values([{ id: "event-ava-welcome", memberId: "demo-ava", kind: "welcome", amount: 100, note: "Founding member welcome grant" }, { id: "event-ava-earned", memberId: "demo-ava", choreId: "chore-4", kind: "earned", amount: 35, note: "Completed: Assemble a hallway shoe rack" }, { id: "event-mateo-welcome", memberId: "demo-mateo", kind: "welcome", amount: 100, note: "Founding member welcome grant" }, { id: "event-mateo-spent", memberId: "demo-mateo", choreId: "chore-4", kind: "spent", amount: -35, note: "Requested: Assemble a hallway shoe rack" }]).onConflictDoNothing(); } },
  { table: choreMessages, createTable: sql`create table if not exists ${choreMessages} (id text primary key, chore_id text not null, sender_id text not null, body text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now())`, createIndexes: [sql`create index if not exists chore_messages_chore_idx on ${choreMessages} (chore_id, created_at)`, sql`create index if not exists chore_messages_sender_idx on ${choreMessages} (sender_id)`] },
]);

export async function getMember(id: string): Promise<Member | null> { await moduleReady; const [row] = await db.select().from(members).where(eq(members.id, id)).limit(1); return row ?? null; }
export async function getDashboard(id: string) { await moduleReady; const member = await getMember(id); const openChores = await db.select().from(chores).where(eq(chores.status, "open")).orderBy(desc(chores.createdAt)).limit(10); const myChores = member ? await db.select().from(chores).where(or(eq(chores.postedBy, id), eq(chores.claimedBy, id))).orderBy(desc(chores.createdAt)).limit(20) : []; const activity = member ? await db.select().from(creditEvents).where(eq(creditEvents.memberId, id)).orderBy(desc(creditEvents.createdAt)).limit(20) : []; const memberCount = await db.select({ count: sql<number>`count(*)` }).from(members); return { member, openChores, myChores, activity, memberCount: Number(memberCount[0]?.count ?? 0) }; }
export async function listChores(category?: string) { await moduleReady; return db.select().from(chores).where(category && category !== "All" ? and(eq(chores.status, "open"), eq(chores.category, category)) : eq(chores.status, "open")).orderBy(desc(chores.createdAt)); }
export async function createMember(id: string, displayName: string, neighborhood: string) { await moduleReady; const existing = await getMember(id); if (existing) return existing; const count = await db.select({ count: sql<number>`count(*)` }).from(members); const grant = Number(count[0]?.count ?? 0) < 1000; const [member] = await db.insert(members).values({ id, displayName, neighborhood, credits: grant ? 100 : 0, welcomeGrant: grant }).returning(); if (grant) await db.insert(creditEvents).values({ id: crypto.randomUUID(), memberId: id, kind: "welcome", amount: 100, note: "Founding member welcome grant" }); return member; }
export async function createChore(input: { id: string; title: string; category: string; neighborhood: string; timing: string; details?: string; credits: number; postedBy: string }) { await moduleReady; if (!choreCategorySet.has(input.category)) throw new HttpError(400, "Choose a supported chore category"); if (input.credits < 1 || !Number.isInteger(input.credits)) throw new HttpError(400, "Credits must be a positive whole number"); const member = await getMember(input.postedBy); if (!member) throw new HttpError(403, "Join ChoreLoop before posting a chore"); const [chore] = await db.insert(chores).values(input).returning(); return chore; }
export async function claimChore(id: string, memberId: string, isAdmin = false) { await moduleReady; const claimant = await getMember(memberId); if (!claimant) throw new HttpError(403, "Join ChoreLoop before accepting a chore"); const [chore] = await db.select().from(chores).where(eq(chores.id, id)).limit(1); if (!chore) throw new HttpError(404, "Chore not found"); if (chore.status !== "open") throw new HttpError(409, "This chore is no longer open"); if (chore.postedBy === memberId && !isAdmin) throw new HttpError(400, "You cannot claim your own chore"); const [updated] = await db.update(chores).set({ status: "claimed", claimedBy: memberId }).where(and(eq(chores.id, id), eq(chores.status, "open"))).returning(); return updated; }
export async function updateChore(id: string, memberId: string, input: { title: string; category: string; neighborhood: string; timing: string; details?: string; credits: number }, isAdmin = false) { await moduleReady; if (!choreCategorySet.has(input.category)) throw new HttpError(400, "Choose a supported chore category"); if (!input.title.trim() || !input.neighborhood.trim() || !input.timing.trim()) throw new HttpError(400, "Title, neighborhood, and timing are required"); if (input.credits < 1 || !Number.isInteger(input.credits)) throw new HttpError(400, "Credits must be a positive whole number"); const [chore] = await db.select().from(chores).where(eq(chores.id, id)).limit(1); if (!chore) throw new HttpError(404, "Chore not found"); if (chore.postedBy !== memberId && !isAdmin) throw new HttpError(403, "Only the chore owner or an admin can edit this chore"); if (chore.status === "completed") throw new HttpError(409, "Completed chores cannot be edited"); const [updated] = await db.update(chores).set({ ...input, details: input.details?.trim() || null }).where(eq(chores.id, id)).returning(); return updated; }
export async function completeChore(id: string, memberId: string) { await moduleReady; return db.transaction(async (tx) => { const [chore] = await tx.select().from(chores).where(eq(chores.id, id)).limit(1); if (!chore || chore.postedBy !== memberId || chore.status !== "claimed" || !chore.claimedBy) throw new HttpError(409, "Only the chore owner can complete a claimed chore"); const [claimant] = await tx.select().from(members).where(eq(members.id, chore.claimedBy)).limit(1); if (!claimant) throw new HttpError(409, "Claiming member is unavailable"); await tx.update(chores).set({ status: "completed" }).where(eq(chores.id, id)); await tx.update(members).set({ credits: sql`${members.credits} + ${chore.credits}` }).where(eq(members.id, chore.claimedBy)); await tx.update(members).set({ credits: sql`${members.credits} - ${chore.credits}` }).where(eq(members.id, memberId)); await tx.insert(creditEvents).values([{ id: crypto.randomUUID(), memberId: chore.claimedBy, choreId: id, kind: "earned", amount: chore.credits, note: `Completed: ${chore.title}` }, { id: crypto.randomUUID(), memberId, choreId: id, kind: "spent", amount: -chore.credits, note: `Requested: ${chore.title}` }]); return { ...chore, status: "completed" as const }; }); }

export async function listChoreMessages(choreId: string, memberId: string) { await moduleReady; const [chore] = await db.select().from(chores).where(eq(chores.id, choreId)).limit(1); if (!chore) throw new HttpError(404, "Chore not found"); if (!chore.claimedBy || !["claimed", "completed"].includes(chore.status) || (chore.postedBy !== memberId && chore.claimedBy !== memberId)) throw new HttpError(403, "Only exchange participants can view this chat"); const messages = await db.select().from(choreMessages).where(eq(choreMessages.choreId, choreId)).orderBy(choreMessages.createdAt); const people = await db.select().from(members).where(or(eq(members.id, chore.postedBy), eq(members.id, chore.claimedBy))); const names = new Map(people.map((person) => [person.id, person.displayName])); return messages.map((message) => ({ ...message, senderName: names.get(message.senderId) ?? "ChoreLoop member" })); }
export async function sendChoreMessage(choreId: string, senderId: string, body: string) { await moduleReady; const cleanBody = body.trim(); if (!cleanBody || cleanBody.length > 2000) throw new HttpError(400, "Message must be 1–2,000 characters"); const [chore] = await db.select().from(chores).where(eq(chores.id, choreId)).limit(1); if (!chore) throw new HttpError(404, "Chore not found"); if (chore.status !== "claimed" || !chore.claimedBy || (chore.postedBy !== senderId && chore.claimedBy !== senderId)) throw new HttpError(403, "Chat is available only to the poster and accepted helper"); const [message] = await db.insert(choreMessages).values({ id: crypto.randomUUID(), choreId, senderId, body: cleanBody }).returning(); const sender = await getMember(senderId); return { ...message, senderName: sender?.displayName ?? "ChoreLoop member" }; }
