/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationRouteImport } from './routes/station'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ApiMembersRouteImport } from './routes/api/members'
import { Route as ApiManifestRouteImport } from './routes/api/manifest'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiChoresRouteImport } from './routes/api/chores'
import { Route as ApiChoreChatRouteImport } from './routes/api/chore-chat'
import { Route as AppPostRouteImport } from './routes/_app.post'
import { Route as AppMyChoresRouteImport } from './routes/_app.my-chores'
import { Route as AppDiscoverRouteImport } from './routes/_app.discover'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'

const StationRoute = StationRouteImport.update({
  id: '/station',
  path: '/station',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiMembersRoute = ApiMembersRouteImport.update({
  id: '/api/members',
  path: '/api/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManifestRoute = ApiManifestRouteImport.update({
  id: '/api/manifest',
  path: '/api/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChoresRoute = ApiChoresRouteImport.update({
  id: '/api/chores',
  path: '/api/chores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChoreChatRoute = ApiChoreChatRouteImport.update({
  id: '/api/chore-chat',
  path: '/api/chore-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPostRoute = AppPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => AppRoute,
} as any)
const AppMyChoresRoute = AppMyChoresRouteImport.update({
  id: '/my-chores',
  path: '/my-chores',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/monitor': typeof MonitorRoute
  '/review': typeof ReviewRoute
  '/station': typeof StationRoute
  '/activity': typeof AppActivityRoute
  '/discover': typeof AppDiscoverRoute
  '/my-chores': typeof AppMyChoresRoute
  '/post': typeof AppPostRoute
  '/api/chore-chat': typeof ApiChoreChatRoute
  '/api/chores': typeof ApiChoresRoute
  '/api/health': typeof ApiHealthRoute
  '/api/manifest': typeof ApiManifestRoute
  '/api/members': typeof ApiMembersRoute
  '/api/auth/me': typeof ApiAuthMeRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/monitor': typeof MonitorRoute
  '/review': typeof ReviewRoute
  '/station': typeof StationRoute
  '/activity': typeof AppActivityRoute
  '/discover': typeof AppDiscoverRoute
  '/my-chores': typeof AppMyChoresRoute
  '/post': typeof AppPostRoute
  '/api/chore-chat': typeof ApiChoreChatRoute
  '/api/chores': typeof ApiChoresRoute
  '/api/health': typeof ApiHealthRoute
  '/api/manifest': typeof ApiManifestRoute
  '/api/members': typeof ApiMembersRoute
  '/': typeof AppIndexRoute
  '/api/auth/me': typeof ApiAuthMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/monitor': typeof MonitorRoute
  '/review': typeof ReviewRoute
  '/station': typeof StationRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/my-chores': typeof AppMyChoresRoute
  '/_app/post': typeof AppPostRoute
  '/api/chore-chat': typeof ApiChoreChatRoute
  '/api/chores': typeof ApiChoresRoute
  '/api/health': typeof ApiHealthRoute
  '/api/manifest': typeof ApiManifestRoute
  '/api/members': typeof ApiMembersRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/me': typeof ApiAuthMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/monitor'
    | '/review'
    | '/station'
    | '/activity'
    | '/discover'
    | '/my-chores'
    | '/post'
    | '/api/chore-chat'
    | '/api/chores'
    | '/api/health'
    | '/api/manifest'
    | '/api/members'
    | '/api/auth/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/monitor'
    | '/review'
    | '/station'
    | '/activity'
    | '/discover'
    | '/my-chores'
    | '/post'
    | '/api/chore-chat'
    | '/api/chores'
    | '/api/health'
    | '/api/manifest'
    | '/api/members'
    | '/'
    | '/api/auth/me'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/monitor'
    | '/review'
    | '/station'
    | '/_app/activity'
    | '/_app/discover'
    | '/_app/my-chores'
    | '/_app/post'
    | '/api/chore-chat'
    | '/api/chores'
    | '/api/health'
    | '/api/manifest'
    | '/api/members'
    | '/_app/'
    | '/api/auth/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MonitorRoute: typeof MonitorRoute
  ReviewRoute: typeof ReviewRoute
  StationRoute: typeof StationRoute
  ApiChoreChatRoute: typeof ApiChoreChatRoute
  ApiChoresRoute: typeof ApiChoresRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiManifestRoute: typeof ApiManifestRoute
  ApiMembersRoute: typeof ApiMembersRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/station': {
      id: '/station'
      path: '/station'
      fullPath: '/station'
      preLoaderRoute: typeof StationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/members': {
      id: '/api/members'
      path: '/api/members'
      fullPath: '/api/members'
      preLoaderRoute: typeof ApiMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manifest': {
      id: '/api/manifest'
      path: '/api/manifest'
      fullPath: '/api/manifest'
      preLoaderRoute: typeof ApiManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chores': {
      id: '/api/chores'
      path: '/api/chores'
      fullPath: '/api/chores'
      preLoaderRoute: typeof ApiChoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chore-chat': {
      id: '/api/chore-chat'
      path: '/api/chore-chat'
      fullPath: '/api/chore-chat'
      preLoaderRoute: typeof ApiChoreChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/post': {
      id: '/_app/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof AppPostRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-chores': {
      id: '/_app/my-chores'
      path: '/my-chores'
      fullPath: '/my-chores'
      preLoaderRoute: typeof AppMyChoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppMyChoresRoute: typeof AppMyChoresRoute
  AppPostRoute: typeof AppPostRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppMyChoresRoute: AppMyChoresRoute,
  AppPostRoute: AppPostRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MonitorRoute: MonitorRoute,
  ReviewRoute: ReviewRoute,
  StationRoute: StationRoute,
  ApiChoreChatRoute: ApiChoreChatRoute,
  ApiChoresRoute: ApiChoresRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiManifestRoute: ApiManifestRoute,
  ApiMembersRoute: ApiMembersRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
